[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
orange_vesting = "HsVbUZkThpaJWZzbNb9nHc4DbQFWv6qALwob7Nbm2vNP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/moganesanm/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
